var portfolioItems=[
    {
        name: 'burgermeetsfries',
        fullName: 'burger meets fries',
        category: 'mockups',
        color: 'purple',
        detailsUrl: 'p-m-burgermeetsfries.html',
        goal: "Burger Meets Fries is a ficticious, satirical dating app created solely for entertainment purposes. The idea started out as a joke among friends; a parody of popular dating app, Coffee Meets Bagel. With the idea being a completely hypothetical product, I took full creative reins.",
    },
    {
        name: 'enerknolrto',
        fullName: 'enerknol & rto insider',
        category: 'branding',
        color: 'blue',
        detailsUrl: 'p-b-enerknol-rto.html',
        goal: "EnerKnol was aiming to increase their presence through an advertising agreement with partner RTO Insider. The ad would be included in RTO Insider's digital publication. The ad needed to reflect their product's core features and maintain all logo designs and branding colors.",
    },
    {
        name: 'nyew',
        fullName: 'new york energy week',
        category: 'branding',
        color: 'navy',
        detailsUrl: 'p-b-nyew2016.html',
        goal: "EnerKnol was in need of an update to their branding material for their annual industry event, New York Energy Week. They wanted a solution that would highlight the event, as well as pointing back to the parent company. Their requirements included maintaining the logo designs and branding colors.",
    },
    {
        name: 'apexmoldremoval',
        fullName: 'apex mold removal',
        category: 'websites',
        color: 'green',
        detailsUrl: 'p-w-apexmoldremoval.html',
        goal: "Apex Mold Specialists is a service company that deals with mold remediation. They were in need of an update to their prior website, which was written entirely in HTML. They wanted a solution to easily manage the content on their website and increase their online presence. Their requirements included maintaining the logo designs and branding colors.",
    },
    {
        name: 'uniquebysk',
        fullName: 'unique products by s&k gifts',
        category: 'websites',
        color: 'white',
        detailsUrl: 'p-w-uniquebysk.html',
        goal: "Unique Products by S&amp;K Gifts is a wholesale company that offers products from multiple manufacturers. They wanted a solution that would allow them to offer these products on an online website that would take orders from both their staff, as well as their customer base. Their requirements included the ability to set order minimums, sales rep tracking, and a user-friendly, modern design to attract customers.",
    },
    {
        name: 'meimeibakery',
        fullName: 'mei mei bakery',
        category: 'websites',
        color: 'pink',
        detailsUrl: 'p-w-meimei.html',
        goal: "Mei Mei Bakery is a local bakery that offers foods and drinks in my neighborhood. They wanted an online presence to display their food menu and attract potential customers.",
    },
    {
        name: 'crownsalesusa',
        fullName: 'crown sales usa',
        category: 'websites',
        color: 'black',
        detailsUrl: 'p-w-crownsalesusa.html',
        goal: "Crown Sales USA is a wholesale conglomerate that offers products from multiple manufacturers. They wanted a solution that would allow them to offer these products on an online website that would take orders from both their staff, as well as their customer base. Their requirements also included the ability to separate these products by manufacturer, as well as the ability to set order minimums, based on the supplier.",
    },
    {
        name: 'suntaste',
        fullName: 'sun taste',
        category: 'branding',
        color: 'orange',
        detailsUrl: 'p-b-suntaste.html',
        goal: "Sun Taste is a wholesale company that offers various frozen seafood products. They wanted an eye-catching cardboard container design for one of their top sellers, the Atlantic Surf Clam.",
    },
    {
        name: 'megawireless',
        fullName: 'mega wireless',
        category: 'branding',
        color: 'white',
        detailsUrl: 'p-b-megawireless.html',
        goal: "Mega Wireless is a wholesale mobile device accessories distributor with custom case designs. They wanted a new eye-catching logo for the customers who visit the stores of their clientele.",
    },
    {
        name: 'smalleye',
        fullName: 'atlantic king',
        category: 'branding',
        color: 'blue',
        detailsUrl: 'p-b-smalleye.html',
        goal: "Atlantic King is a wholesale company that offers various frozen seafood products. They wanted an eye-catching design to use on the polybag container for one of their top sellers, the Smalleye Croaker.",
    },
    {
        name: 'everydayvitamin',
        fullName: 'everyday vitamin',
        category: 'branding',
        color: 'red',
        detailsUrl: 'p-b-everydayvitamin.html',
        goal: "Everyday Vitamin is a health-conscious online pharmacy that had just put in an order for the latest set of fad drugs from weight loss giant, Metabolic Nutrition. They wanted a campaign to advertise these new drugs to their customer base, as well as needing a new advert for their Clicksor campaign.",
    },
    {
        name: 'atlanticking',
        fullName: 'atlantic king',
        category: 'branding',
        color: 'blue',
        detailsUrl: 'p-b-atlanticking.html',
        goal: "Atlantic King is a wholesale company that offers various frozen seafood products. They wanted an eye-catching logo to represent their brand.",
    },
    {
        name: 'conchking',
        fullName: 'conch king',
        category: 'branding',
        color: 'navy',
        detailsUrl: 'p-b-conchking.html',
        goal: "Conch King is a wholesale company that offers various frozen seafood products. They wanted an eye-catching logo to draw attention to their reputation as a distributor of high quality seafood.",
    },
]